/**
 * 模型种子数据
 * 每个模型关联一个提供商，并配置模型类型和参数
 */
export const models = [
  {
    providerName: 'OpenAI Official',
    name: 'gpt-4o',
    displayName: 'GPT-4o',
    modelType: 'chat',
    config: {},
    isActive: true,
    isDefault: true,
  },
  {
    providerName: 'OpenAI Official',
    name: 'gpt-4o-mini',
    displayName: 'GPT-4o Mini',
    modelType: 'chat',
    config: {},
    isActive: true,
    isDefault: false,
  },
  {
    providerName: 'OpenAI Official',
    name: 'text-embedding-3-small',
    displayName: 'Text Embedding 3 Small',
    modelType: 'embedding',
    config: { dimensions: 1024 },
    isActive: true,
    isDefault: true,
  },
  {
    providerName: 'Anthropic Official',
    name: 'claude-3-5-sonnet-20241022',
    displayName: 'Claude 3.5 Sonnet',
    modelType: 'chat',
    config: {},
    isActive: true,
    isDefault: false,
  },
  {
    providerName: 'Ollama Local',
    name: 'llama3.2',
    displayName: 'Llama 3.2',
    modelType: 'chat',
    config: {},
    isActive: true,
    isDefault: false,
  },
  {
    providerName: 'Ollama Local',
    name: 'nomic-embed-text',
    displayName: 'Nomic Embed Text',
    modelType: 'embedding',
    config: {},
    isActive: true,
    isDefault: false,
  },
  {
    providerName: 'DeepSeek Official',
    name: 'deepseek-v4-pro',
    displayName: 'DeepSeek V4 Pro',
    modelType: 'chat',
    config: {},
    isActive: true,
    isDefault: false,
  },
  {
    providerName: 'DeepSeek Official',
    name: 'deepseek-v4-flash',
    displayName: 'DeepSeek V4 Flash',
    modelType: 'chat',
    config: {},
    isActive: true,
    isDefault: false,
  },
]
